engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
ratings:
   paths:
   - "src/**/*"
   - "**.php"
   - "**.module"
   - "**.inc"
exclude_paths:
- "tests/**/*"
- "sami_configuration.php"
