language: php

php:
  - 5.6
  - 7
  - hhvm

sudo: false

install:
  - composer install --no-interaction

script:
  - composer test

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then travis_retry vendor/bin/test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then travis_retry vendor/bin/coveralls -v; fi

addons:
  code_climate:
    repo_token: 0a7405e53e8a9416e5e801ac18df80453b7af1fa8659251753ba0a5ffcd4a4a7
